name: publiccode.yml validation

on: [pull_request, push]

jobs:
  publiccode_yml_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
      - uses: italia/publiccode-parser-action@360aac457ebcdee729754996a1816df662879cb0 # v1.3.3
        with:
          publiccode: 'publiccode.yml'
