name: publiccode.yml validation

on: [pull_request, push]

jobs:
  publiccode_yml_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.1
      - uses: italia/publiccode-parser-action@44a711e642b242be0cfc042b49f870ad2f9464fb # v1.4.3
        with:
          publiccode: 'publiccode.yml'
