name: Tests

on: [ push, pull_request ]

# Declare default permissions as read only.
permissions: read-all

env:
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:
  run_tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository code
        uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5 # v6.0.0
        with:
          fetch-depth: 1

      - name: Cache npm dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('client/npm-shrinkwrap.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Cache pip dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install git
        run: |
          sudo apt update -q
          sudo apt install -y git

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          ./.github/workflows/scripts/run_tests.sh
