name: Tests

on: [ push, pull_request ]

# Declare default permissions as read only.
permissions: read-all

env:
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:
  run_tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          fetch-depth: 1

      - name: Cache npm dependencies
        uses: actions/cache@638ed79f9dc94c1de1baef91bcab5edaa19451f4 # v4.2.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('client/npm-shrinkwrap.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Cache pip dependencies
        uses: actions/cache@638ed79f9dc94c1de1baef91bcab5edaa19451f4 # v4.2.4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install git
        run: |
          sudo apt update -q
          sudo apt install -y git

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          ./.github/workflows/scripts/run_tests.sh
