name: Tests

on: [ push, pull_request ]

# Declare default permissions as read only.
permissions: read-all

env:
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:
  run_tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.1
        with:
          fetch-depth: 1

      - name: Cache npm dependencies
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('client/npm-shrinkwrap.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Cache pip dependencies
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install git
        run: |
          sudo apt update -q
          sudo apt install -y git

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          ./.github/workflows/scripts/run_tests.sh
